name: Reusable deploy workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - development
          - test-2

jobs:
 deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
        run: deploy --build ${{ inputs.build_id }} --target ${{ inputs.deploy_target }}
